flarepoint/routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

// Login/Logout Routes
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
// Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

Route::group(['middleware' => ['auth']], function () {
    /*
     * Main
     */
    Route::get('/', 'PagesController@dashboard');
    Route::get('dashboard', 'PagesController@dashboard')->name('dashboard');

    /*
     * Users
     */
    Route::group(['prefix' => 'users'], function () {
        Route::get('/data', 'UsersController@anyData')->name('users.data');
        Route::get('/taskdata/{id}', 'UsersController@taskData')->name('users.taskdata');
        Route::get('/leaddata/{id}', 'UsersController@leadData')->name('users.leaddata');
        Route::get('/clientdata/{id}', 'UsersController@clientData')->name('users.clientdata');
        Route::get('/users', 'UsersController@users')->name('users.users');
    });
    Route::resource('users', 'UsersController');

    /*
    * Roles
    */
    Route::resource('roles', 'RolesController');

    /*
     * Clients
     */
    Route::group(['prefix' => 'clients'], function () {
        Route::get('/data', 'ClientsController@anyData')->name('clients.data');
        Route::get('/my', 'ClientsController@my')->name('clients.my');
        Route::get('/mydata', 'ClientsController@myData')->name('clients.mydata');
        Route::post('/create/cvrapi', 'ClientsController@cvrapiStart');
        Route::post('/upload/{id}', 'DocumentsController@upload');
        Route::patch('/updateassign/{id}', 'ClientsController@updateAssign');
    });
    Route::resource('clients', 'ClientsController');
    Route::resource('documents', 'DocumentsController');

    /*
     * Contacts
     */
    Route::group(['prefix' => 'contacts'], function () {
        Route::get('/data', 'ContactsController@anyData')->name('contacts.data');
        Route::get('/my', 'ContactsController@my')->name('contacts.my');
        Route::get('/mydata', 'ContactsController@myData')->name('contacts.mydata');
    });
    Route::resource('contacts', 'ContactsController');

    /*
     * Tasks
     */
    Route::group(['prefix' => 'tasks'], function () {
        Route::get('/data', 'TasksController@anyData')->name('tasks.data');
        Route::get('/my', 'TasksController@my')->name('tasks.my');
        Route::get('/mydata', 'TasksController@myData')->name('tasks.mydata');
        Route::patch('/updatestatus/{id}', 'TasksController@updateStatus');
        Route::patch('/updateassign/{id}', 'TasksController@updateAssign');
        Route::post('/updatetime/{id}', 'TasksController@updateTime');
    });
    Route::resource('tasks', 'TasksController');

    /*
     * Leads
     */
    Route::group(['prefix' => 'leads'], function () {
        Route::get('/data', 'LeadsController@anyData')->name('leads.data');
        Route::get('/my', 'LeadsController@my')->name('leads.my');
        Route::get('/mydata', 'LeadsController@myData')->name('leads.mydata');
        Route::patch('/updateassign/{id}', 'LeadsController@updateAssign');
        Route::patch('/updatestatus/{id}', 'LeadsController@updateStatus');
        Route::patch('/updatefollowup/{id}', 'LeadsController@updateFollowup')->name('leads.followup');
    });
    Route::resource('leads', 'LeadsController');
    Route::post('/comments/{type}/{id}', 'CommentController@store');
    /*
     * Settings
     */
    Route::group(['prefix' => 'settings'], function () {
        Route::get('/', 'SettingsController@index')->name('settings.index');
        Route::patch('/permissionsUpdate', 'SettingsController@permissionsUpdate');
        Route::patch('/overall', 'SettingsController@updateOverall');
    });

    /*
     * Departments
     */
    Route::resource('departments', 'DepartmentsController');

    /*
     * Integrations
     */
    Route::group(['prefix' => 'integrations'], function () {
        Route::get('Integration/slack', 'IntegrationsController@slack');
    });
    Route::resource('integrations', 'IntegrationsController');

    /*
     * Notifications
     */
    Route::group(['prefix' => 'notifications'], function () {
        Route::post('/markread', 'NotificationsController@markRead')->name('notification.read');
        Route::get('/markall', 'NotificationsController@markAll');
        Route::get('/{id}', 'NotificationsController@markRead');
    });

    /*
     * Invoices
     */
    Route::group(['prefix' => 'invoices'], function () {
        Route::post('/updatepayment/{id}', 'InvoicesController@updatePayment')->name('invoice.payment.date');
        Route::post('/reopenpayment/{id}', 'InvoicesController@reopenPayment')->name('invoice.payment.reopen');
        Route::post('/sentinvoice/{id}', 'InvoicesController@updateSentStatus')->name('invoice.sent');
        Route::post('/newitem/{id}', 'InvoicesController@newItem')->name('invoice.new.item');
    });
    Route::resource('invoices', 'InvoicesController');
});

flarepoint/app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Client extends Model
{
    protected $fillable = [
        'name',
        'vat',
        'primary_email',
        'billing_address1',
        'billing_address2',
        'billing_city',
        'billing_state',
        'billing_zipcode',
        'billing_country',
        'shipping_address1',
        'shipping_address2',
        'shipping_city',
        'shipping_state',
        'shipping_zipcode',
        'shipping_country',
        'primary_number',
        'secondary_number',
        'industry_id',
        'company_type',
        'user_id',
    ];

    public function getFormattedBillingAddressAttribute()
    {
        $address = '';

        if ($this->billing_address1 || $this->billing_city || $this->billing_zipcode) {
            if ($this->billing_address1) {
                $address .= htmlspecialchars($this->billing_address1).'<br/>';
            }
            if ($this->billing_address2) {
                $address .= htmlspecialchars($this->billing_address2).'<br/>';
            }
            if ($this->billing_city || $this->billing_state || $this->billing_zipcode) {
                if ($this->billing_city) {
                    $address .= $this->billing_city.'&nbsp;';
                }
                if ($this->billing_state) {
                    $address .= $this->billing_state.'&nbsp;';
                }
                if ($this->billing_zipcode) {
                    $address .= $this->billing_zipcode;
                }
            }
            if ($this->billing_country) {
                $address .= '<br/>'.$this->billing_country;
            }

            return $address;
        } else {
            return null;
        }
    }

    public function getFormattedShippingAddressAttribute()
    {
        $address = '';

        if ($this->shipping_address1 || $this->shipping_city || $this->shipping_zipcode) {
            if ($this->shipping_address1) {
                $address .= htmlspecialchars($this->shipping_address1).'<br/>';
            }
            if ($this->shipping_address2) {
                $address .= htmlspecialchars($this->shipping_address2).'<br/>';
            }
            if ($this->shipping_city || $this->shipping_state || $this->shipping_zipcode) {
                if ($this->shipping_city) {
                    $address .= $this->shipping_city.'&nbsp;';
                }
                if ($this->shipping_state) {
                    $address .= $this->shipping_state.'&nbsp;';
                }
                if ($this->shipping_zipcode) {
                    $address .= $this->shipping_zipcode;
                }
            }
            if ($this->shipping_country) {
                $address .= '<br/>'.$this->shipping_country;
            }

            return $address;
        } else {
            return null;
        }
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function tasks()
    {
        return $this->hasMany(Task::class, 'client_id', 'id')
            ->orderBy('status', 'asc')
            ->orderBy('created_at', 'desc');
    }

    public function leads()
    {
        return $this->hasMany(Lead::class, 'client_id', 'id')
            ->orderBy('status', 'asc')
            ->orderBy('created_at', 'desc');
    }

    public function contacts()
    {
        return $this->hasMany(Contact::class, 'client_id', 'id')
            ->orderBy('name', 'asc')
            ->orderBy('created_at', 'desc');
    }

    public function documents()
    {
        return $this->hasMany(Document::class, 'client_id', 'id');
    }

    public function invoices()
    {
        return $this->hasMany(Invoice::class);
    }

    public function industry()
    {
        return $this->belongsTo(Industry::class, 'industry_id');
    }

    public function getAssignedUserAttribute()
    {
        return User::findOrFail($this->user_id);
    }

    public function scopeMy($query)
    {
        return $query->where('user_id', Auth::id());
    }
}

flarepoint/resources/views/partials/clientheader.blade.php
<div class="col-md-6">

    <h1 class="moveup">{{$client->name}}</h1>

    <!--Client info leftside-->
    <div class="contactleft">
        @if($client->primary_number != "")
            <p><span class="glyphicon glyphicon-phone-alt" aria-hidden="true" data-toggle="tooltip"
                     title=" {{ __('Primary Number') }} " data-placement="left"> </span>
                <a href="tel:{{$client->primary_number}}">{{$client->primary_number}}</a></p>
        @endif
        @if($client->secondary_number != "")
            <p><span class="glyphicon glyphicon-print" aria-hidden="true" data-toggle="tooltip"
                     title="{{ __('Secondary/FAX Number') }}" data-placement="left"> </span>
                <a href="tel:{{$client->secondary_number}}">{{$client->secondary_number}}</a></p>
        @endif
        @if($client->primary_email != "")
            <p><span class="glyphicon glyphicon-envelope" aria-hidden="true" data-toggle="tooltip"
                     title="{{ __('mail') }}" data-placement="left"> </span>
                <a href="mailto:{{$client->primary_email}}" data-toggle="tooltip" data-placement="left">{{$client->primary_email}}</a></p>
        @endif
        @if($client->vat != "")
                <!--Company-->
        <p><span class="glyphicon glyphicon-cloud" aria-hidden="true" data-toggle="tooltip"
                 title="{{ __('vat') }}" data-placement="left"> </span> {{$client->vat}}</p>
        @endif
        @if($client->industry != "")
                <!--Industry-->
        <p><span class="glyphicon glyphicon-briefcase" aria-hidden="true" data-toggle="tooltip"
                 title="{{ __('Industry') }}"data-placement="left"> </span> {{$client->industry->name}}</p>
        @endif
        @if($client->company_type!= "")
                <!--Company Type-->
        <p><span class="glyphicon glyphicon-globe" aria-hidden="true" data-toggle="tooltip"
                 title="{{ __('Company type') }}" data-placement="left"> </span>
            {{$client->company_type}}</p>
        @endif
    </div>
    <!--Client info leftside END-->

    <!--Client info rightside-->
    <div class="contactright">
        @if($client->formatted_billing_address)
            <p>
                <span class="glyphicon glyphicon-home" aria-hidden="true" data-toggle="tooltip"
                     title="{{ __('Billing Address') }}" data-placement="left"></span> Billing Address
            </p>
            <p>
                {!! $client->formatted_billing_address !!}
            </p>
        @endif
        @if($client->formatted_shipping_address)
            <p>
                <span class="glyphicon glyphicon-home" aria-hidden="true" data-toggle="tooltip"
                     title="{{ __('Shipping Address') }}" data-placement="left"></span> Shipping Address
            </p>
            <p>
                {!! $client->formatted_shipping_address !!}
            </p>
        @endif
    </div>
    <!--Client info rightside END-->

</div>

flarepoint/resources/views/partials/comments.blade.php
<?php $subject instanceof \App\Models\Task ? $instance = 'task' : $instance = 'lead' ?>

<div class="panel panel-primary shadow">
    <div class="panel-heading"><p>{{$subject->title}}</p></div>
    <div class="panel-body">
        <p>{{$subject->description }}</p>
        <p class="smalltext">{{ __('Created at') }}:
            {{ date('d F, Y, H:i:s', strtotime($subject->created_at))}}
            @if($subject->updated_at != $subject->created_at)
                <br/>{{ __('Modified') }}: {{date('d F, Y, H:i:s', strtotime($subject->updated_at))}}
            @endif</p>
    </div>
</div>

<?php $count = 0;?>
<?php $i = 1 ?>
@foreach($subject->comments as $comment)
    <div class="panel panel-primary shadow" style="margin-top:15px; padding-top:10px;">
        <div class="panel-body">
            <p class="smalltext">#{{$i++}}</p>
            <p>  {{ $comment->description }}</p>
            <p class="smalltext">{{ __('Comment by') }}: <a
                        href="{{route('users.show', $comment->user->id)}}"> {{$comment->user->name}} </a>
            </p>
            <p class="smalltext">{{ __('Created at') }}:
                {{ date('d F, Y, H:i:s', strtotime($comment->created_at))}}
                @if($comment->updated_at != $comment->created_at)
                        <br/>{{ __('Modified') }} : {{date('d F, Y, H:i:s', strtotime($comment->updated_at))}}
                @endif</p>
        </div>
    </div>
@endforeach
<br/>

@if($instance == 'task')
    {!! Form::open(array('url' => array('/comments/task',$subject->id, ))) !!}
    <div class="form-group">
        {!! Form::textarea('description', null, ['class' => 'form-control', 'id' => 'comment-field']) !!}

        {!! Form::submit( __('Add Comment') , ['class' => 'btn btn-primary']) !!}
    </div>
    {!! Form::close() !!}
@else
    {!! Form::open(array('url' => array('/comments/lead',$lead->id, ))) !!}
    <div class="form-group">
        {!! Form::textarea('description', null, ['class' => 'form-control', 'id' => 'comment-field']) !!}

        {!! Form::submit( __('Add Comment') , ['class' => 'btn btn-primary']) !!}
    </div>
    {!! Form::close() !!}
@endif

@push('scripts')
    <script>
        $('#comment-field').atwho({
            at: "@",
            limit: 5, 
            delay: 400,
            callbacks: {
                remoteFilter: function (t, e) {
                    t.length <= 2 || $.getJSON("/users/users", {q: t}, function (t) {
                        e(t)
                    })
                }
            }
        })
    </script>
@endpush

flarepoint/resources/views/partials/dashboardone.blade.php
<br/><br/>
<div class="col-sm-6">

    <div class="box box-primary">
        <div class="box-header with-border">
            <h4 class="box-title"
            >
                {{ __('Tasks each month') }}
            </h4>
            <div class="box-tools pull-right">
                <button type="button" id="collapse1" class="btn btn-box-tool" data-toggle="collapse"
                        data-target="#collapseOne"><i id="toggler1" class="fa fa-minus"></i>
                </button>
            </div>
        </div>
        <div id="collapseOne" class="panel-collapse">
            <div class="box-body">
                <div>
                    <graphline class="chart" :labels="{{json_encode($createdTaskEachMonths)}}"
                               :values="{{json_encode($taskCreated)}}"
                               :valuesextra="{{json_encode($taskCompleted)}}"></graphline>
                </div>
            </div>
        </div>
    </div>
    <div class="box box-primary">
        <div class="box-header with-border">
            <h4 class="box-title"
            >
               {{ __('Lead each month') }}
            </h4>
            <div class="box-tools pull-right">
                <button type="button" id="collapse2" class="btn btn-box-tool" data-toggle="collapse"
                        data-target="#collapseTwo"><i id="toggler2" class="fa fa-minus"></i>
                </button>
            </div>
        </div>
        <div id="collapseTwo" class="panel-collapse">
            <div class="box-body">
                <div>
                    <graphline class="chart" :labels="{{json_encode($createdLeadEachMonths)}}"
                               :values="{{json_encode($leadCreated)}}"
                               :valuesextra="{{json_encode($leadsCompleted)}}"></graphline>

                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-sm-6">

    <div class="col-lg-12">
        <!-- Info Boxes Style 2 -->
        <div class="info-box bg-yellow">
            <span class="info-box-icon"><i class="ion ion-ios-book-outline"></i></span>

            <div class="info-box-content">
                <span class="info-box-text"> {{ __('All Tasks') }} </span>
                <span class="info-box-number">{{$allCompletedTasks}} / {{$alltasks}}</span>

                <div class="progress">
                    <div class="progress-bar" style="width: {{$totalPercentageTasks}}%"></div>
                </div>
                  <span class="progress-description">
                    {{number_format($totalPercentageTasks, 0)}}% {{ __('Completed') }}
                  </span>
            </div>
            <!-- /.info-box-content -->
        </div>
    </div>
    <div class="col-lg-12">
        <!-- /.info-box -->
        <div class="info-box bg-red">
            <span class="info-box-icon"><i class="ion ion-stats-bars"></i></span>

            <div class="info-box-content">
                <span class="info-box-text">{{ __('All Leads') }}</span>
                <span class="info-box-number">{{$allCompletedLeads}} / {{$allleads}}</span>

                <div class="progress">
                    <div class="progress-bar" style="width: {{$totalPercentageLeads}}%"></div>
                </div>
                  <span class="progress-description">
                    {{number_format($totalPercentageLeads, 0)}}% {{ __('Completed') }}
                  </span>
            </div>
            <!-- /.info-box-content -->
        </div>

    </div>
    <div class="col-sm-12">

        <div class="box box-primary">
            <div class="box-header with-border">
                <h4 class="box-title"
                >
                    {{ __('Users') }}
                </h4>
                <div class="box-tools pull-right">

                </div>
            </div>
            <div id="collapseOne" class="panel-collapse">

                @foreach($users as $user)
                    <div class="col-lg-1">
                        @if($user->isOnline())
                            <i class="dot-online" data-toggle="tooltip" title="Online" data-placement="left"></i>
                        @else
                            <i class="dot-offline" data-toggle="tooltip" title="Offline" data-placement="left"></i>
                        @endif
                        <a href="{{route('users.show', $user->id)}}">
                            <img class="small-profile-picture" data-toggle="tooltip" title="{{$user->name}}"
                                 data-placement="left"
                                 @if($user->image_path != "")
                                 src="images/{{$companyname}}/{{$user->image_path}}"
                                 @else
                                 src="images/default_avatar.jpg"
                                    @endif />
                        </a>

                    </div>

                @endforeach

            </div>
        </div>
    </div>


</div>
</div>


<!-- Info boxes -->
<div class="row movedown">
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-aqua"><i class="ion ion-ios-book-outline"></i></span>

            <div class="info-box-content">
                <span class="info-box-text">{{ __('Tasks completed today') }}</span>
                <span class="info-box-number">{{$completedTasksToday}}
                    <small></small></span>
            </div>
            <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-red"><i class="ion ion-ios-book-outline"></i></span>

            <div class="info-box-content">
                <span class="info-box-text">{{ __('Tasks created today') }}</span>
                <span class="info-box-number">{{$createdTasksToday}}</span>
            </div>
            <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>
    <!-- /.col -->

    <!-- fix for small devices only -->
    <div class="clearfix visible-sm-block"></div>

    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-green"><i class="ion ion-stats-bars"></i></span>

            <div class="info-box-content">
                <span class="info-box-text">{{ __('Leads completed today') }}</span>
                <span class="info-box-number">{{$completedLeadsToday}}</span>
            </div>
            <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-yellow"><i class="ion ion-stats-bars"></i></span>

            <div class="info-box-content">
                <span class="info-box-text">{{ __('Leads created today') }}</span>
                <span class="info-box-number">{{$createdLeadsToday}}</span>
            </div>
            <!-- /.info-box-content -->
        </div>
    </div>
</div>
<!-- /.info-box -->
    

flarepoint/resources/views/partials/dashboardtwo.blade.php
<div class="col-lg-8">
    <div class="col-lg-6">
        <!-- Info Boxes Style 2 -->
        <div class="info-box bg-yellow">
            <span class="info-box-icon"><i class="ion ion-ios-book-outline"></i></span>

            <div class="info-box-content">
                <span class="info-box-text">All Tasks</span>
                <span class="info-box-number">{{$allCompletedTasks}} / {{$alltasks}}</span>

                <div class="progress">
                    <div class="progress-bar" style="width: {{$totalPercentageTasks}}%"></div>
                </div>
                  <span class="progress-description">
                    {{number_format($totalPercentageTasks, 0)}}% Completed
                  </span>
            </div>
            <!-- /.info-box-content -->
        </div>
    </div>
    <div class="col-lg-6">
        <!-- /.info-box -->
        <div class="info-box bg-red">
            <span class="info-box-icon"><i class="ion ion-stats-bars"></i></span>

            <div class="info-box-content">
                <span class="info-box-text">All Leads</span>
                <span class="info-box-number">{{$allCompletedLeads}} / {{$allleads}}</span>

                <div class="progress">
                    <div class="progress-bar" style="width: {{$totalPercentageLeads}}%"></div>
                </div>
                  <span class="progress-description">
                    {{number_format($totalPercentageLeads, 0)}}% Completed
                  </span>
            </div>
            <!-- /.info-box-content -->
        </div>

    </div>
</div>

<div class="col-lg-4">
    <h4>All Users</h4>
    @foreach($users as $user)
        <div class="col-lg-1">
            @if($user->isOnline())
                <i class="dot-online" data-toggle="tooltip" title="Online" data-placement="left"></i>
            @else
                <i class="dot-offline" data-toggle="tooltip" title="Offline" data-placement="left"></i>
            @endif
            <a href="{{route('users.show', $user->id)}}">
                <img class="small-profile-picture" data-toggle="tooltip" title="{{$user->name}}" data-placement="left"
                     @if($user->image_path != "")
                     src="images/{{$companyname}}/{{$user->image_path}}"
                     @else
                     src="images/default_avatar.jpg"
                        @endif />
            </a>
        </div>


    @endforeach

</div>
</div>

<div class="row">


    <button id="collapse-init" class="btn btn-primary">
        Disable accordion behavior
    </button>
    <br/><br/>
    <div class="col-sm-6">

        <div class="box box-primary">
            <div class="box-header with-border">
                <h4 class="box-title"
                >
                    Tasks created each Month
                </h4>
                <div class="box-tools pull-right">
                    <button type="button" id="collapse1" class="btn btn-box-tool" data-toggle="collapse"
                            data-target="#collapseOne"><i id="toggler1" class="fa fa-minus"></i>
                    </button>
                </div>
            </div>
            <div id="collapseOne" class="panel-collapse">
                <div class="box-body">
                    <div>
                        <graphline class="chart" :labels="{{json_encode($createdTaskEachMonths)}}"
                                   :values="{{json_encode($taskCreated)}}"
                                   :valuesextra="{{json_encode($taskCompleted)}}"></graphline>
                    </div>
                </div>
            </div>
        </div>
        <div class="box box-primary">
            <div class="box-header with-border">
                <h4 class="box-title"
                >
                    Created leads each month
                </h4>
                <div class="box-tools pull-right">
                    <button type="button" id="collapse2" class="btn btn-box-tool" data-toggle="collapse"
                            data-target="#collapseTwo"><i id="toggler2" class="fa fa-minus"></i>
                    </button>
                </div>
            </div>
            <div id="collapseTwo" class="panel-collapse">
                <div class="box-body">
                    <div>
                        <graphline class="chart" :labels="{{json_encode($createdLeadEachMonths)}}"
                                   :values="{{json_encode($leadCreated)}}"></graphline>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-6">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h4 class="box-title"
                >
                    Tasks completed each month
                </h4>
                <div class="box-tools pull-right">
                    <button type="button" id="collapse3" class="btn btn-box-tool" data-toggle="collapse"
                            data-target="#collapseThree"><i id="toggler3" class="fa fa-minus"></i>
                    </button>
                </div>
            </div>
            <div id="collapseThree" class="panel-collapse">
                <div class="box-body">
                    <div>
                        <graphline class="chart" :labels="{{json_encode($completedTaskEachMonths)}}"
                                   :values="{{json_encode($taskCompleted)}}"></graphline>
                    </div>
                </div>
            </div>
        </div>


        <div class="box box-primary">
            <div class="box-header with-border">
                <h4 class="box-title"
                >
                    Leads completed each month
                </h4>
                <div class="box-tools pull-right">
                    <button type="button" id="collapse4" class="btn btn-box-tool" data-toggle="collapse"
                            data-target="#collapseFour"><i id="toggler4" class="fa fa-minus"></i>
                    </button>
                </div>
            </div>
            <div id="collapseFour" class="panel-collapse">
                <div class="box-body">
                    <div>
                        <graphline class="chart" :labels="{{json_encode($completedLeadEachMonths)}}"
                                   :values="{{json_encode($leadsCompleted)}}"></graphline>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>


<!-- Info boxes -->
<div class="row">
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-aqua"><i class="ion ion-ios-book-outline"></i></span>

            <div class="info-box-content">
                <span class="info-box-text">Tasks completed today</span>
                <span class="info-box-number">{{$completedTasksToday}}
                    <small></small></span>
            </div>
            <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-red"><i class="ion ion-ios-book-outline"></i></span>

            <div class="info-box-content">
                <span class="info-box-text">Tasks created today</span>
                <span class="info-box-number">{{$createdTasksToday}}</span>
            </div>
            <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>
    <!-- /.col -->

    <!-- fix for small devices only -->
    <div class="clearfix visible-sm-block"></div>

    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-green"><i class="ion ion-stats-bars"></i></span>

            <div class="info-box-content">
                <span class="info-box-text">Leads Completed today</span>
                <span class="info-box-number">{{$completedLeadsToday}}</span>
            </div>
            <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-yellow"><i class="ion ion-stats-bars"></i></span>

            <div class="info-box-content">
                <span class="info-box-text">Leads created today</span>
                <span class="info-box-number">{{$createdLeadsToday}}</span>
            </div>
            <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    
    